# Generated by Django 5.2.6 on 2025-09-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='banners/')),
                ('designation', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(upload_to='company_logos/')),
                ('salary', models.CharField(max_length=50)),
                ('desciption', models.TextField()),
                ('contact1', models.CharField(max_length=15)),
                ('contact2', models.CharField(max_length=15)),
            ],
        ),
    ]
