# Generated by Django 5.2.6 on 2025-09-20 12:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['order'], 'verbose_name': 'Card', 'verbose_name_plural': 'Cards'},
        ),
        migrations.AddField(
            model_name='card',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='desciption',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
